binaries = ["dropbear", "mkfifo", "chmod"]
paths = "/etc/dropbear"
mount_devpts = true

[masks.custom_init]
"ugrd.base.console" = "custom_init"

[imports.config_processing]
"dropbear" = [ "_process_dropbear_authorized_keys" ]

[imports.build_tasks]
"dropbear" = [ "add_dropbear_keys", "add_unlock_script", "add_console_prompt_script" ]

[imports.build_final]
"dropbear" = [ "dropbear_finalize" ]

[imports.custom_init]
"dropbear" = [ "dropbear_init" ]

[custom_parameters]
dropbear_authorized_keys = "Path"
